#!/usr/bin/env python3

"""
My own homegrown build script.
Because waf, SCons, autotools, and CMake all made me angry.
"""

import sys
import os
import subprocess

def invoke(command):
    print(' '.join(command))
    subprocess.check_call(command)

def files_under(path):
    result = []
    for dirpath, dirnames, filenames in os.walk(path):
        result.extend(os.path.join(dirpath, filename) for filename in filenames)
    return result

def compile_vala(sources, target, pkgs=[], defs=[]):
    invoke(['valac', '-g', '-d', 'target', '-o', target] +
           ['--pkg=%s' % pkg for pkg in pkgs] +
           ['--define=%s' % define for define in defs] +
           sources)

def main():
    pkgs = ['gtk+-2.0', 'gee-1.0', 'gexiv2', 'libxml-2.0', 'libsoup-2.4']
    main_sources = [f for f in files_under('src') if f.endswith('.vala')]
    compile_vala(sources=main_sources, target='xmpedit', pkgs=pkgs)

    compile_vala(sources=main_sources, target='xmpedit_test', pkgs=pkgs, defs=['TEST'])
    invoke(['gtester', '--verbose', 'target/xmpedit_test'])

if __name__ == '__main__':
    main()
